import type { Scene } from "./types";

export const mockScenes: Scene[] = [
  {
    id: "scene-coffee",
    slug: "coffee-order",
    title: { "zh-CN": "咖啡店点餐", en: "Ordering coffee" },
    subtitle: {
      "zh-CN": "自然完成点单、选择杯型和付款",
      en: "Order, choose a size, and pay naturally",
    },
    category: "daily",
    coverTone: "coffee",
    coverMark: "☕",
    difficulty: 2,
    estimatedMinutes: 8,
    lessonCount: 10,
    favorite: false,
  },
  {
    id: "scene-airport",
    slug: "airport-check-in",
    title: { "zh-CN": "机场值机", en: "Airport check-in" },
    subtitle: {
      "zh-CN": "办理值机、托运行李并确认登机口",
      en: "Check in, drop bags, and confirm the gate",
    },
    category: "travel",
    coverTone: "airport",
    coverMark: "✈",
    difficulty: 3,
    estimatedMinutes: 10,
    lessonCount: 15,
    favorite: true,
  },
  {
    id: "scene-meeting",
    slug: "work-meeting",
    title: { "zh-CN": "工作会议", en: "Work meeting" },
    subtitle: {
      "zh-CN": "汇报进度、提出问题并确认下一步",
      en: "Share progress, raise issues, and align next steps",
    },
    category: "work",
    coverTone: "meeting",
    coverMark: "◫",
    difficulty: 4,
    estimatedMinutes: 12,
    lessonCount: 10,
    favorite: false,
  },
  {
    id: "scene-restaurant",
    slug: "restaurant-order",
    title: { "zh-CN": "餐厅点餐", en: "At a restaurant" },
    subtitle: {
      "zh-CN": "询问菜品、表达偏好并完成结账",
      en: "Ask about dishes, share preferences, and pay",
    },
    category: "daily",
    coverTone: "restaurant",
    coverMark: "♨",
    difficulty: 2,
    estimatedMinutes: 8,
    lessonCount: 12,
    favorite: false,
  },
  {
    id: "scene-shopping",
    slug: "shopping",
    title: { "zh-CN": "购物", en: "Shopping" },
    subtitle: {
      "zh-CN": "询问尺码、颜色、价格和退换政策",
      en: "Ask about size, color, price, and returns",
    },
    category: "daily",
    coverTone: "shopping",
    coverMark: "◈",
    difficulty: 2,
    estimatedMinutes: 8,
    lessonCount: 8,
    favorite: false,
  },
  {
    id: "scene-metro",
    slug: "metro-directions",
    title: { "zh-CN": "地铁问路", en: "Metro directions" },
    subtitle: {
      "zh-CN": "询问路线、换乘方式和到站时间",
      en: "Ask for routes, transfers, and arrival time",
    },
    category: "travel",
    coverTone: "metro",
    coverMark: "▰",
    difficulty: 2,
    estimatedMinutes: 8,
    lessonCount: 8,
    favorite: false,
  },
  {
    id: "scene-hotel",
    slug: "hotel-check-in",
    title: { "zh-CN": "酒店入住", en: "Hotel check-in" },
    subtitle: {
      "zh-CN": "确认预订、房型、早餐和退房时间",
      en: "Confirm booking, room, breakfast, and checkout",
    },
    category: "travel",
    coverTone: "hotel",
    coverMark: "▦",
    difficulty: 3,
    estimatedMinutes: 10,
    lessonCount: 8,
    favorite: true,
  },
  {
    id: "scene-presentation",
    slug: "project-update",
    title: { "zh-CN": "项目汇报", en: "Project update" },
    subtitle: {
      "zh-CN": "说明项目结果、风险与后续计划",
      en: "Present results, risks, and the next plan",
    },
    category: "work",
    coverTone: "presentation",
    coverMark: "↗",
    difficulty: 4,
    estimatedMinutes: 12,
    lessonCount: 8,
    favorite: false,
  },
];

export function findScene(identifier: string) {
  return mockScenes.find(
    (scene) => scene.id === identifier || scene.slug === identifier,
  );
}
