ALTER TABLE `user_profiles`
ADD COLUMN `voice` VARCHAR(191) NOT NULL DEFAULT 'marin',
ADD COLUMN `speechSpeed` DOUBLE NOT NULL DEFAULT 1,
ADD COLUMN `correctionFrequency` VARCHAR(191) NOT NULL DEFAULT 'balanced',
ADD COLUMN `learningGoal` VARCHAR(191) NOT NULL DEFAULT 'daily',
ADD COLUMN `showChinese` BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN `autoPlay` BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN `saveAudio` BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN `saveConversation` BOOLEAN NOT NULL DEFAULT true;
