ALTER TABLE "user_profiles"
ADD COLUMN "voice" TEXT NOT NULL DEFAULT 'marin',
ADD COLUMN "speechSpeed" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "correctionFrequency" TEXT NOT NULL DEFAULT 'balanced',
ADD COLUMN "learningGoal" TEXT NOT NULL DEFAULT 'daily',
ADD COLUMN "showChinese" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "autoPlay" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "saveAudio" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "saveConversation" BOOLEAN NOT NULL DEFAULT true;
